version: '3.7'

services:

  db:
    env_file:
        - .env
    image: postgres:12.1-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
