version: '3.7'

services:

  db:
    env_file:
        - .env
    image: postgres:12.1-alpine
    restart: always
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
